- name: Upgrade SumoCollector to 19.216-38
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:

  - get_url:
      url: http://spacewalk.copart.com/pub/SumoCollector-19.216-38.x86_64.rpm
      dest: /tmp/

  - yum:
      name: /tmp/SumoCollector-19.216-38.x86_64.rpm
      state: present
